version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.53.0
    resource_class: small
    steps:
      - checkout
      - run: rustc --version; cargo --version; rustup --version
      - run: cargo generate-lockfile
      - run: cargo install cargo-junit
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          cargo junit --name results.xml
      - run: mkdir test-results; mv results.xml test-results
      - store_test_results:
          path: test-results

